---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.10

before_install:
  - gem install bundler -v 1.17.2

script:
  - bin/setup

jobs:
  include:
    - stage: test
      if: branch != gem_release
      script:
        - bundle exec rake spec
    - stage: publish
      if: branch = gem_release
      script:
        - gem build tolgee_liquid.gemspec
        - gem_file=$(ls tolgee_liquid-*.gem)
        - gem push "${gem_file}" --host https://rubygems.org --key "${RUBYGEMS_API_KEY}"

branches:
  only:
    - main
    - gem_release

