---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.10

before_install:
  - gem install bundler -v 1.17.2

script:
  - bin/setup
  - bundle exec rake spec
  - gem build tolgee_liquid.gemspec

before_deploy:
  - export TRAVIS_TAG=$(git describe --tags --abbrev=0)

deploy:
  provider: rubygems
  api_key: "$RUBYGEMS_API_KEY"
  on:
    tags: true

branches:
  only:
    - main
    - /^v\d+(\.\d+(\.\d+)?)?$/
